#!/bin/bash
# check if the script is run inside ../ISA-filter-design
case "$PWD" in
    *ISA-filter-design );;
    * ) 
        echo "Error: script must be run in the repository root directory"
        exit 1
        ;;
esac

# define constants
USER_HOST="isa22@led-x3850-2.polito.it"
PORT="10020"
SSH_SOCKET=~/".ssh/$USER_HOST"
REMOTE_ROOT="/home/isa22/lab1"

# create master SSH connection
ssh -M -f -N -o ControlPath="$SSH_SOCKET" -p $PORT "$USER_HOST"

# offer selection between different actions
PS3="Select the number corresponding to the action needed and press enter (defalut = 1):"
options=("Copy all bidirectional" "Copy source files to server" "Copy testbench files to server" "Copy results from server")
select opt in "${options[@]}"
do 
    case $opt in 
        2)
            scp -o ControlPath="$SSH_SOCKET" -P $PORT HW_filter/VHDL/*.vhd "$USER_HOST":"$REMOTE_ROOT"/src
            break;;
        3)
            scp -o ControlPath="$SSH_SOCKET" -P $PORT HW_filter/VHDL/testbench/* "$USER_HOST":"$REMOTE_ROOT"/tb
            break
            ;;
        4)
            scp -o ControlPath="$SSH_SOCKET" -P $PORT "$USER_HOST":"$REMOTE_ROOT"/common/results-hw.txt common/
            break
            ;;
        *)
            scp -o ControlPath="$SSH_SOCKET" -P $PORT HW_filter/VHDL/*.vhd "$USER_HOST":"$REMOTE_ROOT"/src
            scp -o ControlPath="$SSH_SOCKET" -P $PORT HW_filter/VHDL/testbench/* "$USER_HOST":"$REMOTE_ROOT"/tb
            scp -o ControlPath="$SSH_SOCKET" -P $PORT "$USER_HOST":"$REMOTE_ROOT"/common/results-hw.txt common/
            break
            ;;
        
    esac
done

# close master connection
ssh -S "$SSH_SOCKET" -O exit "$USER_HOST"